default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: debian
  password: ruby1
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: RoR_development

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: RoR_production
