source 'https://rubygems.org'
ruby '2.4.1'

gem 'rails', '~> 5.2.4'
gem 'sqlite3', '~> 1.3.13'

group :development, :test do
  gem 'rspec-rails', '~> 3.7'
  gem 'capybara'
  gem 'database_cleaner-active_record'
end

group :development do
  gem 'web-console'
end
